ccflags-y += -I$(srctree)/drivers/input/touchscreen/atmel/

#obj-$(CONFIG_MXT_PLIGIN_CAL) += plugin_cal.o

obj-y += nubia_tp_cmn.o

#ifdef CONFIG_MXT_DEBUG_ENABLE
#KBUILD_CFLAGS	+= -DDEBUG
#endif

#MAKEFLAGS += --include-dir=

