#
# Makefile for the Synaptics DSX touchscreen driver.
#

# Each configuration option enables a list of files.

obj-$(CONFIG_TOUCHSCREEN_NUBIA_SYNAPTICS_S1302_I2C) += synaptics_dsx_i2c.o
obj-$(CONFIG_TOUCHSCREEN_NUBIA_SYNAPTICS_S1302_SPI) += synaptics_dsx_spi.o
obj-$(CONFIG_TOUCHSCREEN_NUBIA_SYNAPTICS_S1302_RMI_HID_I2C) += synaptics_dsx_rmi_hid_i2c.o
obj-$(CONFIG_TOUCHSCREEN_NUBIA_SYNAPTICS_S1302_CORE) += synaptics_dsx_core.o
obj-$(CONFIG_TOUCHSCREEN_NUBIA_SYNAPTICS_S1302_RMI_DEV) += synaptics_dsx_rmi_dev.o
obj-$(CONFIG_TOUCHSCREEN_NUBIA_SYNAPTICS_S1302_FW_UPDATE) += synaptics_dsx_fw_update.o
obj-$(CONFIG_TOUCHSCREEN_NUBIA_SYNAPTICS_S1302_TEST_REPORTING) += synaptics_dsx_test_reporting.o
obj-$(CONFIG_TOUCHSCREEN_NUBIA_SYNAPTICS_S1302_PROXIMITY) += synaptics_dsx_proximity.o
obj-$(CONFIG_TOUCHSCREEN_NUBIA_SYNAPTICS_S1302_ACTIVE_PEN) += synaptics_dsx_active_pen.o
obj-$(CONFIG_TOUCHSCREEN_NUBIA_SYNAPTICS_S1302_GESTURE) += synaptics_dsx_gesture.o
obj-$(CONFIG_TOUCHSCREEN_NUBIA_SYNAPTICS_S1302_VIDEO) += synaptics_dsx_video.o
